/* Generated By:JavaCC: Do not edit this line. RTFParserConstants.java */
package com.etranslate.tm.processing.rtf;

public interface RTFParserConstants {

  int EOF = 0;
  int BACKSLASH = 1;
  int HEX_ESCAPE = 2;
  int LBRACE = 7;
  int RBRACE = 8;
  int NON_BREAKING_SPACE = 9;
  int OPTIONAL_HYPHEN = 10;
  int NON_BREAKING_HYPHEN = 11;
  int ESCAPED_NEWLINE = 12;
  int ESCAPED_CARRIAGE_RETURN = 13;
  int IGNORABLE_DESTINATION = 14;
  int FORMULA_CHARACTER = 15;
  int INDEX_SUBENTRY = 16;
  int ESCAPED_LBRACE = 17;
  int ESCAPED_RBRACE = 18;
  int ESCAPED_BACKSLASH = 19;
  int CONTROL_SYM = 20;
  int TEXT = 21;
  int HEX_DIGIT = 22;
  int HEX_CHAR = 23;
  int PAR = 29;
  int LINE = 30;
  int U = 31;
  int UC = 32;
  int F = 33;
  int CS = 34;
  int FCHARSET = 35;
  int PLAIN = 36;
  int PC = 37;
  int PCA = 38;
  int MAC = 39;
  int RTF = 40;
  int ANSI = 41;
  int ANSICPG = 42;
  int DEFF = 43;
  int FROMTEXT = 44;
  int FROMHTML = 45;
  int FBIDIS = 46;
  int INFO = 47;
  int REVTBL = 48;
  int PNTEXT = 49;
  int FONTTBL = 50;
  int COLORTBL = 51;
  int PNSECLVL = 52;
  int LISTTABLE = 53;
  int STYLESHEET = 54;
  int TAB = 55;
  int ZWJ = 56;
  int ZWNJ = 57;
  int EMDASH = 58;
  int ENDASH = 59;
  int EMSPACE = 60;
  int ENSPACE = 61;
  int QMSPACE = 62;
  int BULLET = 63;
  int LQUOTE = 64;
  int RQUOTE = 65;
  int LTRMARK = 66;
  int RTLMARK = 67;
  int LDBLQUOTE = 68;
  int RDBLQUOTE = 69;
  int BIN = 70;
  int CONTROL_WORD = 71;
  int DIGIT = 72;
  int CW_VAL = 73;
  int TEXT_CONTROL_DELIMITER = 74;

  int CONTROL_VALUE = 0;
  int CONTROL = 1;
  int HEX = 2;
  int DEFAULT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\"\\\\\"",
    "\"\\\\\\\'\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\u0000\"",
    "\"{\"",
    "\"}\"",
    "\"\\\\~\"",
    "\"\\\\-\"",
    "\"\\\\_\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\"",
    "\"\\\\*\"",
    "\"\\\\|\"",
    "\"\\\\:\"",
    "\"\\\\{\"",
    "\"\\\\}\"",
    "\"\\\\\\\\\"",
    "<CONTROL_SYM>",
    "<TEXT>",
    "<HEX_DIGIT>",
    "<HEX_CHAR>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\u0000\"",
    "\"par\"",
    "\"line\"",
    "\"u\"",
    "\"uc\"",
    "\"f\"",
    "\"cs\"",
    "\"fcharset\"",
    "\"plain\"",
    "\"pc\"",
    "\"pca\"",
    "\"mac\"",
    "\"rtf\"",
    "\"ansi\"",
    "\"ansicpg\"",
    "\"deff\"",
    "\"fromtext\"",
    "\"fromhtml\"",
    "\"fbidis\"",
    "\"info\"",
    "\"revtbl\"",
    "\"pntext\"",
    "\"fonttbl\"",
    "\"colortbl\"",
    "\"pnseclvl\"",
    "\"listtable\"",
    "\"stylesheet\"",
    "\"tab\"",
    "\"zwj\"",
    "\"zwnj\"",
    "\"emdash\"",
    "\"endash\"",
    "\"emspace\"",
    "\"enspace\"",
    "\"qmspace\"",
    "\"bullet\"",
    "\"lquote\"",
    "\"rquote\"",
    "\"ltrmark\"",
    "\"rtlmark\"",
    "\"ldblquote\"",
    "\"rdblquote\"",
    "\"bin\"",
    "<CONTROL_WORD>",
    "<DIGIT>",
    "<CW_VAL>",
    "<TEXT_CONTROL_DELIMITER>",
  };

}
